"""add import_batches and transactions tables

Revision ID: 6707d7d88bbf
Revises: a77d60e8cabd
Create Date: 2026-07-27 22:01:48.567641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6707d7d88bbf'
down_revision: Union[str, Sequence[str], None] = 'a77d60e8cabd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('skipped_duplicate_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('bsb_number', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('narration', sa.String(), nullable=False),
    sa.Column('cheque_number', sa.String(), nullable=True),
    sa.Column('debit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_dup_lookup', 'transactions', ['account_number', 'transaction_date', 'narration', 'debit', 'credit', 'balance'], unique=False)
    op.create_index(op.f('ix_transactions_import_batch_id'), 'transactions', ['import_batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_import_batch_id'), table_name='transactions')
    op.drop_index('ix_transactions_dup_lookup', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
