"""add category kind and budget

Revision ID: 7bb1999e6c44
Revises: f206a4443d15
Create Date: 2026-07-31 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb1999e6c44'
down_revision: Union[str, Sequence[str], None] = 'f206a4443d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows to 'expense' - kept in place
    # permanently (not dropped after backfill) so the migrated schema keeps
    # matching what Base.metadata.create_all produces for the test suite.
    op.add_column('categories', sa.Column('kind', sa.String(), nullable=False, server_default='expense'))
    op.add_column('categories', sa.Column('budget_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_column('categories', 'budget_amount')
    op.drop_column('categories', 'kind')
    # ### end Alembic commands ###
