"""add accounts and categories tables

Revision ID: cee3a8016863
Revises: 51b622a5b3bb
Create Date: 2026-07-31 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee3a8016863'
down_revision: Union[str, Sequence[str], None] = '51b622a5b3bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('bsb_number', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number', name='uq_accounts_account_number')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_categories_name')
    )
    op.add_column('transactions', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_foreign_key('fk_transactions_account_id_accounts', 'transactions', 'accounts', ['account_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_transactions_category_id_categories', 'transactions', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transactions_category_id_categories', 'transactions', type_='foreignkey')
    op.drop_constraint('fk_transactions_account_id_accounts', 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_column('transactions', 'category_id')
    op.drop_column('transactions', 'account_id')
    op.drop_table('categories')
    op.drop_table('accounts')
    # ### end Alembic commands ###
