"""add category rules

Revision ID: f206a4443d15
Revises: cee3a8016863
Create Date: 2026-07-31 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f206a4443d15'
down_revision: Union[str, Sequence[str], None] = 'cee3a8016863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('narration_pattern', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('min_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_category_rules_category_id_categories', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_rules_category_id'), 'category_rules', ['category_id'], unique=False)
    op.add_column('transactions', sa.Column('categorized_by_rule_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_categorized_by_rule_id'), 'transactions', ['categorized_by_rule_id'], unique=False)
    op.create_foreign_key('fk_transactions_categorized_by_rule_id_category_rules', 'transactions', 'category_rules', ['categorized_by_rule_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transactions_categorized_by_rule_id_category_rules', 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_categorized_by_rule_id'), table_name='transactions')
    op.drop_column('transactions', 'categorized_by_rule_id')
    op.drop_index(op.f('ix_category_rules_category_id'), table_name='category_rules')
    op.drop_table('category_rules')
    # ### end Alembic commands ###
